name: cbesdesktop
description: CENTER FOR BIOMAS AND ENERGY CENTER (CBES) Desktop Application for controlling and monitoring the Research Center parameters

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-429.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  connectivity_plus: ^3.0.2
  mqtt_client: ^9.7.2
  http: ^0.13.5
  provider: ^6.0.4
  charts_flutter: ^0.12.0
  syncfusion_flutter_gauges: ^20.3.59
  kdgaugeview: ^1.0.4
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.3.60

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/